<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Abstractions\Persistence\Repositories\**" />
    <EmbeddedResource Remove="Abstractions\Persistence\Repositories\**" />
    <None Remove="Abstractions\Persistence\Repositories\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Services\" />
    <Folder Include="Common\Abstractions\Persistence\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\YK.Auth.Application\YK.Auth.Application.csproj" />
    <ProjectReference Include="..\..\Core\YK.Auth.Domain\YK.Auth.Domain.csproj" />
  </ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
